services:
  caddy:
    image: ghcr.io/walzen-group/caddy-netcup
    container_name: caddy
    restart: unless-stopped
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "2019":"2019"
    volumes:
      - /opt/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /opt/caddy/data:/data
      - /opt/caddy/config:/config
      - /opt/caddy/static:/static
    networks:
      - local

networks:
  local:
    external: true
